### ISSUE TITLE
fastlane apprepo init not initializing Repofile

### ISSUE THREAD

**Issue by gouen95** [suculent/fastlane-plugin-apprepo#11]
As of example image provided below, I used fastlane to install apprepo as a plugin, but I am having difficulty generating the Repofile.

Example image :
<img width="637" alt="screen shot 2018-08-17 at 11 26 01 am" src="https://user-images.githubusercontent.com/21040866/44246343-5855e200-a210-11e8-8c8e-78911ba5b88b.png">

**Comment by gouen95** [comment]
Update, I've solved the problem above, but now I'm facing a problem where my server requires me to enter a different port. Is there a way to define the specific port?

<img width="1124" alt="screen shot 2018-08-17 at 12 09 54 pm" src="https://user-images.githubusercontent.com/21040866/44247382-91915080-a216-11e8-8470-c3526777fcc2.png">

**Comment by suculent** [comment]
Added host_port option into Repofile since 0.5.0.
