### ISSUE TITLE
fastlane apprepo plugin init and all other functions don't work 

### ISSUE THREAD

**Issue by iurii-iaremenko** [suculent/fastlane-plugin-apprepo#12]
fastlane apprepo init

[
[✔] 🚀
+-------------------------+---------+-----------------------------------+
|                             Used plugins                              |
+-------------------------+---------+-----------------------------------+
| Plugin                  | Version | Action                            |
+-------------------------+---------+-----------------------------------+
| fastlane-plugin-ftp     | 0.1.3   | ftp                               |
| fastlane-plugin-apprepo | 0.5.5   | download_manifest init run submit |
+-------------------------+---------+-----------------------------------+

[12:29:29]: ------------------------------
[12:29:29]: --- Step: default_platform ---
[12:29:29]: ------------------------------
+------------------+-----+
|      Lane Context      |
+------------------+-----+
| DEFAULT_PLATFORM | ios |
+------------------+-----+
[12:29:29]: Could not find lane 'apprepo init'. Available lanes: ios testflight_release, ios upload_to_FTP, ios upload_to_CDN

**Comment by iurii-iaremenko** [comment]
this plugin is useless, implemented own sftp uploading.

**Comment by oklimberg** [comment]
I experience the same problems with version 0.5.5.
Running `fastlane apprepo init` does not initializes a Repofile inside the project.
Neither does `bundle exec fastlane action init` or putting the init action inside a fastlane lane 'temp' and call it via `bundle exec fastlane temp`.  The last call will actually result in the following errror 
```
bundle exec fastlane foo
[✔] 🚀
+-------------------------+---------+-----------------------------------+
|                             Used plugins                              |
+-------------------------+---------+-----------------------------------+
| Plugin                  | Version | Action                            |
+-------------------------+---------+-----------------------------------+
| fastlane-plugin-apprepo | 0.5.5   | download_manifest init run submit |
+-------------------------+---------+-----------------------------------+

[22:26:20]: ------------------------------
[22:26:20]: --- Step: default_platform ---
[22:26:20]: ------------------------------
[22:26:20]: Driving the lane 'ios foo' 🚀
[22:26:20]: ------------------
[22:26:20]: --- Step: init ---
[22:26:20]: ------------------
[22:26:20]: Unknown method 'command'
+------------------+---------+
|        Lane Context        |
+------------------+---------+
| DEFAULT_PLATFORM | ios     |
| PLATFORM_NAME    | ios     |
| LANE_NAME        | ios foo |
+------------------+---------+
[22:26:20]: To call another action from an action use `other_action.command` instead

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | init             | 0           |
+------+------------------+-------------+

[22:26:20]: fastlane finished with errors

[!] To call another action from an action use `other_action.command` instead`
```

I am using fastlane on a Mac with fastlane version 2.108.0
